language: python
matrix:
    include:
        - python: 2.7
          env: TOX_ENV=py27
        - python: 3.4
          env: TOX_ENV=py34
        - python: 3.5
          env: TOX_ENV=py35
install:
    - "pip install tox coveralls"
script:
    - "tox -e $TOX_ENV"
    - "tox -e pep8"
    - "tox -e pylint"
    - "tox -e docs"
after_success:
    coveralls
